name: Build and Deploy Kivy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk unzip git zip

      - name: Install Buildozer and Android SDK
        run: |
          pip install cython
          pip install buildozer
          sudo apt-get install -y python3-dev build-essential

          # Set up Android SDK
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
          unzip tools.zip
          mv cmdline-tools latest

          # Set environment variables
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

          # Accept licenses and install required tools
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;33.0.2" "build-tools;36.0.0"
          
          # Ensure AIDL is installed
          if [ ! -f "$HOME/android-sdk/build-tools/36.0.0/aidl" ]; then
            echo "AIDL not found, installing..."
            $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;36.0.0"
          fi

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: .buildozer/android/platform/build/dists/TicTacToe/build/outputs/apk/debug/TicTacToe-debug.apk

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository for deployment
        uses: actions/checkout@v3

      - name: Download APK artifact
        uses: actions/download-artifact@v3
        with:
          name: kivy-apk

      - name: Deploy APK
        run: |
          echo "Deploying APK..."

