name: Build and Deploy Kivy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk unzip git zip

      - name: Install Buildozer and Android SDK
        run: |
          pip install cython
          pip install buildozer
          sudo apt-get install -y python3-dev build-essential

          # Install SDK Manager and accept licenses
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
          unzip tools.zip
          mv cmdline-tools latest
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;33.0.2"

      - name: Build APK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          buildozer android debug

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: .buildozer/android/platform/build/dists/your_app_name/build/outputs/apk/debug/your_app_name-debug.apk

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository for deployment
        uses: actions/checkout@v3

      - name: Download APK artifact
        uses: actions/download-artifact@v3
        with:
          name: kivy-apk

      - name: Deploy APK
        run: |
          # Deployment script goes here
          echo "Deploying APK..."
